### PR TITLE
Update to newer mcstats and bukkit APIs

### PR DESCRIPTION
**Pull request by lagnat**

### CODE REVIEW

**Comment by awendland** [comment]
Thanks for sending this pull request in. Would you mind enumerating some of the benefits to updating these plugin versions? Also, are there any breaking changes (the major version of the plugins change, which usually indicates breaking changes occurred).

**Comment by lagnat** [comment]
Updated the bukkit api only to make sure the current code is 1.9 compatible.
No code changes were made so I don't imagine any compatibility issues.
I bumped the java version to 1.7 but that was not entirely necessary.
Updating mcstats is necessary to avoid this error in the console

[11:29:05] [Craft Scheduler Thread - 1/WARN]: org.apache.commons.lang.UnhandledException: Plugin WarpPortals v5.6.3 generated an exception while executing task 70
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at com.mccraftaholics.warpportals.MetricsLite.postPlugin(MetricsLite.java:273)
    at com.mccraftaholics.warpportals.MetricsLite.access$300(MetricsLite.java:50)
    at com.mccraftaholics.warpportals.MetricsLite$1.run(MetricsLite.java:165)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by awendland** [comment]
Is the bukkit 1.9 API backwards compatible to run on Bukkit 1.8 versions?

**Comment by lagnat** [comment]
No, but I didn't add any 1.9 specific code, nor do you have any 1.8 specific code so the pom could have either api.  That change should be innocuous, though testing is always a good idea.

**Comment by awendland** [comment]
Sounds good!

Would you mind resubmitting this pull request without any changes to `WarpPortals_latest.jar`? I try to keep that file tested.

(If I find free time in the next couple months I'll be transitioning all this over to a proper build system on something like Travis CI).

**Comment by awendland** [comment]
Also, would you mind rebasing your history so that it is a single commit detailing the version updates?

Thanks for helping keep this plugin alive!

**Pull request closed without merging**
